#!/bin/bash
source /workspace/.venv/bin/activate

# Source env.sh if available (generated by 'complexa init docker', mounted via code mount)
_env_sh="/workspace/protein-foundation-models/env.sh"
if [[ -f "$_env_sh" ]]; then
  source "$_env_sh"
fi

if [ "$#" -eq 0 ]; then
  exec bash
else
  exec "$@"
fi
